Token truncation fix
mande-labs/trust-drops pull request #5
Opened 2024-05-27 14:45 UTC by Hekku2

This Pull Request changes the handling of number formatting in Dashboard.jsx, because there were a couple of cases where the number wouldn't show enough details for user to be able to destake correct amount of tokens.

Functional changes:

| Input | Previous Output | New Output |
|--|--|--|
| 2.00 | 2.00 | 2.00 |
| 2 | 2.00 | 2.00 |
| 2.1 | 2.10 | 2.00 |
| 1.99 | 1.99 | 1.99 |
| 1.99999 | **2.00** | **1.99999** |
| 1.9999900000 | **2.00** | **1.99999** |

Other important thing (also mentioned in comment as it's not immediately obvious), `toFixed` is not used to pad the length because of the way javascript handles floating point numbers.

2024-05-27 15:12 UTC, prtk418 requested changes

2024-05-27 15:12 UTC, prtk418 commented on trust-drops-ui/src/pages/Dashboard.jsx
> +    while (decimal && decimal.length < precision) {
currently with `amount = 15.9961001 and precision = 4` as input it would output `15.9961001`

lets handle case where `decimal.length > precision` as well, maybe trim in that case

2024-05-27 18:38 UTC, Hekku2 commented on trust-drops-ui/src/pages/Dashboard.jsx
> +    while (decimal && decimal.length < precision) {
Are you sure you want that? That can cause problems if person (like me) has staked value like 0.000001 or similar. I makes it harder / impossible to unstake those values, and those values are still allowed by be contract/token? Or are you planning on reducing from 18 decimals in main net?

I can of course implement that, but I just want to make sure you are aware of the problems it will cause.

2024-05-28 03:37 UTC, prtk418 commented on trust-drops-ui/src/pages/Dashboard.jsx
> +    while (decimal && decimal.length < precision) {
Yes, displaying till 4 decimals is more than enough IMO. We want to keep UI display clean as well. On mainnet the decimals will still be 18.

Instead what we can do is - add a button on stake and unstake form (`MAX`) to allow users unstake all the staked MAND and similarly stake all MAND available from balance. wdyt?

2024-05-28 09:21 UTC, Hekku2 commented on trust-drops-ui/src/pages/Dashboard.jsx
> +    while (decimal && decimal.length < precision) {
I think that would solve the issue and keep the UI display clean!

I'll make that precision fix later today, that MAX-button should probably be implemented in separate PR.

2024-05-28 19:47 UTC, Hekku2 commented on trust-drops-ui/src/pages/Dashboard.jsx
> +          credibility: truncateAmount(data.credScore, 2),
Aah, good point, I forgot to check that. I assume this can be fixed by using it directly, if it's integer.

2024-05-28 19:49 UTC, Hekku2 commented on trust-drops-ui/src/pages/Dashboard.jsx
> +          credibility: truncateAmount(data.credScore, 2),
It should be fixed now, if I understood that correct. I didn't have proper testing data for this, so i had to guess.

2024-05-30 02:23 UTC, prtk418 approved these changes

2024-05-30 02:23 UTC, merged

2024-05-30 02:23 UTC, prtk418 commented
Thanks for the contribution @Hekku2

2024-05-30 06:36 UTC, Hekku2 commented
No problem! And kudos for the project, looking good!